spring.application.name=Khoi_tao_du_an_theo_kien_truc_phan_tang
spring.datasource.url=jdbc:postgresql://localhost:5432/course_db
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true