spring.application.name=BT_Session04

#Config DataSourse
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bt_session04
spring.datasource.username=postgres
spring.datasource.password=1

#Config JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Config
pageSizeCourse=5
