spring.application.name=BT_Session04

#Config DataSourse
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bt_session04
spring.datasource.username=postgres
spring.datasource.password=1

#Config JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD

#Config
pageSizeCourse=5
=======
>>>>>>> c4b39f1be6a603d1182ab456bb21746cf5482a7e
